/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 6cc0185f586fe8bbead16a70281e09c3)
interface __BaseEnv_Env {
  WORKSPACE_BUCKET: R2Bucket;
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  ThinkAgent_Nexp: DurableObjectNamespace /* ThinkAgent_Nexp */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
