/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: bae01283e9c0a361c13e0117f236d1ec)
interface __BaseEnv_Env {
  WORKSPACE_BUCKET: R2Bucket;
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  ThinkAgent_Crazp: DurableObjectNamespace /* ThinkAgent_Crazp */;
  crazp: DurableObjectNamespace /* ThinkAgent_Crazp */;
  SANDBOX: DurableObjectNamespace<import("./src/worker-entry").Sandbox>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker-entry");
    durableNamespaces: "ThinkAgent_Crazp" | "Sandbox";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
