// Generated by `think types`. Do not edit this file directly.
// Re-run `think types` after changing Think agents or Wrangler bindings.
// <think-generated>
declare module "virtual:think/entry" {
  const entry: ExportedHandler<Cloudflare.Env>;
  export default entry;
  export const ThinkAgent_Nexp: (typeof import("./agents/nexp/agent"))["NexpAgent"];
  export const ThinkSubAgent_Nexp_Worker: (typeof import("./agents/nexp/agents/worker/agent"))["NexpWorker"];
}
declare module "virtual:think/router" {
  export const thinkRouter: import("@cloudflare/think/server-entry").ThinkRouter;
}

declare namespace Cloudflare {
  interface Env {
    ThinkAgent_Nexp: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/nexp/agent"))["NexpAgent"]>
    >;
  }
}
// </think-generated>
