// Generated by `think types`. Do not edit this file directly.
// Re-run `think types` after changing Think agents or Wrangler bindings.
// <think-generated>
declare module "virtual:think/entry" {
  const entry: ExportedHandler<Cloudflare.Env>;
  export default entry;
  export const ThinkAgent_Crazp: (typeof import("./agents/crazp/agent"))["CrazpAgent"];
  export const ThinkSubAgent_Crazp_Worker: (typeof import("./agents/crazp/agents/worker/agent"))["CrazpWorker"];
}
declare module "virtual:think/router" {
  export const thinkRouter: import("@cloudflare/think/server-entry").ThinkRouter;
}

declare namespace Cloudflare {
  interface Env {
    ThinkAgent_Crazp: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/crazp/agent"))["CrazpAgent"]>
    >;
  }
}
// </think-generated>
